-- Update existing user to be our admin for sample data
UPDATE public.profiles 
SET nickname = 'FanYueShe Admin' 
WHERE user_id = '43271470-2b48-440f-a1d0-eaaa2b65b6e1';

-- Create sample dinners targeting Western markets with English-friendly content
INSERT INTO public.dinners (
  id,
  created_by,
  title,
  description,
  dinner_time,
  location,
  max_participants,
  food_preferences,
  dietary_restrictions,
  gender_preference,
  personality_tags,
  dinner_mode,
  urgency_level,
  status,
  friends_only
) VALUES 
-- New York area dinners
('10000000-0000-0000-0000-000000000001', '43271470-2b48-440f-a1d0-eaaa2b65b6e1', 
'Authentic Sichuan Hot Pot Experience in Manhattan', 
'Join me for an authentic Sichuan hot pot experience! Perfect for food adventurers who love spicy cuisine. We''ll explore the rich flavors of traditional Chinese hot pot while making new international friends. Great for cultural exchange!',
NOW() + INTERVAL '2 days',
'Manhattan, New York, NY, USA',
4,
ARRAY['川菜', '火锅', '中餐'],
ARRAY['清真'],
'no_preference',
ARRAY['外向', '美食爱好者', '文化探索者'],
'scheduled',
'normal',
'active',
false),

('10000000-0000-0000-0000-000000000002', '43271470-2b48-440f-a1d0-eaaa2b65b6e1',
'Japanese Sushi & Sake Tasting in Brooklyn',
'Discover authentic Japanese cuisine with fellow food enthusiasts! We''ll visit a traditional sushi restaurant and learn about sake pairing. Perfect for anyone interested in Japanese culture and high-quality dining.',
NOW() + INTERVAL '3 days',
'Brooklyn Heights, Brooklyn, NY, USA',
6,
ARRAY['日餐', '寿司', '日式'],
NULL,
'no_preference',
ARRAY['好奇', '高雅', '社交'],
'scheduled',
'normal',
'active',
false),

-- Los Angeles area dinners  
('10000000-0000-0000-0000-000000000003', '43271470-2b48-440f-a1d0-eaaa2b65b6e1',
'Korean BBQ Social in Koreatown LA',
'Experience the best Korean BBQ in LA''s Koreatown! Perfect for meat lovers and those who enjoy interactive dining. We''ll grill, chat, and enjoy traditional Korean side dishes together.',
NOW() + INTERVAL '1 day',
'Koreatown, Los Angeles, CA, USA',
8,
ARRAY['韩餐', '烤肉', '亚洲菜'],
NULL,
'no_preference',
ARRAY['社交', '美食爱好者', '冒险'],
'scheduled',
'normal',
'active',
false),

('10000000-0000-0000-0000-000000000004', '43271470-2b48-440f-a1d0-eaaa2b65b6e1',
'Vegetarian Farm-to-Table Dinner in West Hollywood',
'Join our vegetarian dining group for a sustainable, organic farm-to-table experience. Perfect for health-conscious diners and those interested in sustainable eating.',
NOW() + INTERVAL '4 days',
'West Hollywood, Los Angeles, CA, USA',
4,
ARRAY['素食', '有机', '健康'],
ARRAY['素食主义'],
'no_preference',
ARRAY['健康意识', '环保', '深思熟虑'],
'scheduled',
'normal',
'active',
false),

-- San Francisco Bay Area dinners
('10000000-0000-0000-0000-000000000005', '43271470-2b48-440f-a1d0-eaaa2b65b6e1',
'Tech Professional Networking Dinner in SOMA',
'Calling all tech professionals! Join us for dinner in San Francisco''s SOMA district. Great networking opportunity while enjoying fusion cuisine. Perfect for professionals looking to expand their network.',
NOW() + INTERVAL '5 days',
'SOMA, San Francisco, CA, USA',
6,
ARRAY['融合菜', '国际菜', '现代菜'],
NULL,
'no_preference',
ARRAY['专业', '人脉', '上进'],
'scheduled',
'normal',
'active',
false),

-- Chicago dinners
('10000000-0000-0000-0000-000000000006', '43271470-2b48-440f-a1d0-eaaa2b65b6e1',
'Deep Dish Pizza & Chicago Food Tour',
'Experience Chicago''s famous deep dish pizza and explore the city''s food scene! Perfect for tourists and locals who want to discover authentic Chicago cuisine.',
NOW() + INTERVAL '6 days',
'The Loop, Chicago, IL, USA',
5,
ARRAY['美式', '披萨', '当地菜'],
NULL,
'no_preference',
ARRAY['游客友好', '本地专家', '美食向导'],
'scheduled',
'normal',
'active',
false),

-- International cuisine in Miami
('10000000-0000-0000-0000-000000000007', '43271470-2b48-440f-a1d0-eaaa2b65b6e1',
'Latin Fusion Dinner in South Beach Miami',
'Explore Miami''s vibrant Latin food scene in South Beach! We''ll enjoy fusion dishes that blend traditional Latin flavors with modern techniques. Great for culture enthusiasts!',
NOW() + INTERVAL '3 days',
'South Beach, Miami, FL, USA',
4,
ARRAY['拉丁菜', '融合菜', '热带菜'],
NULL,
'no_preference',
ARRAY['文化', '活力', '海滩爱好者'],
'scheduled',
'normal',
'active',
false),

-- Seattle coffee & dining culture
('10000000-0000-0000-0000-000000000008', '43271470-2b48-440f-a1d0-eaaa2b65b6e1',
'Seattle Coffee Culture & Brunch Experience',
'Dive into Seattle''s famous coffee culture! We''ll start with specialty coffee tasting and end with a delicious Pacific Northwest brunch. Perfect for coffee enthusiasts and brunch lovers.',
NOW() + INTERVAL '2 days',
'Capitol Hill, Seattle, WA, USA',
4,
ARRAY['咖啡', '早午餐', '太平洋西北菜'],
ARRAY['无麸质'],
'no_preference',
ARRAY['咖啡爱好者', '放松', '晨型人'],
'scheduled',
'normal',
'active',
false),

-- Boston area
('10000000-0000-0000-0000-000000000009', '43271470-2b48-440f-a1d0-eaaa2b65b6e1',
'New England Seafood Experience in Boston',
'Taste the best of New England seafood! Fresh lobster, clam chowder, and regional specialties. Perfect for seafood lovers and those wanting to experience Boston''s culinary heritage.',
NOW() + INTERVAL '4 days',
'North End, Boston, MA, USA',
6,
ARRAY['海鲜', '新英格兰菜', '传统菜'],
NULL,
'no_preference',
ARRAY['美食家', '传统', '本地文化'],
'scheduled',
'normal',
'active',
false),

-- Austin, Texas
('10000000-0000-0000-0000-000000000010', '43271470-2b48-440f-a1d0-eaaa2b65b6e1',
'Austin BBQ & Live Music Experience',
'Keep Austin weird! Join us for authentic Texas BBQ followed by live music. Experience the unique culture that makes Austin special. Food, music, and great company!',
NOW() + INTERVAL '5 days',
'East Austin, Austin, TX, USA',
8,
ARRAY['烤肉', '德州菜', '南方菜'],
NULL,
'no_preference',
ARRAY['音乐爱好者', '随意', '文化'],
'scheduled',
'normal',
'active',
false)
ON CONFLICT (id) DO NOTHING;