// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://patwwdmjidcvfldncdtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhdHd3ZG1qaWRjdmZsZG5jZHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODQyNTcsImV4cCI6MjA3MDA2MDI1N30.ZVDgxSTv7-FSor8eeOXsZXR_iR83IOdVQ3Xoe_bxnkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});